# Generated by Django 5.2.6 on 2025-09-24 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=100)),
                ('s_form', models.CharField(max_length=100)),
                ('past', models.CharField(max_length=100)),
                ('past_participle', models.CharField(max_length=100)),
                ('ing', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=100)),
                ('example', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
