# Generated by Django 5.2.6 on 2025-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth0_id', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('profile_picture_url', models.URLField()),
                ('current_level', models.CharField(max_length=20)),
                ('words_know_count', models.IntegerField(default=0)),
                ('words_learned_count', models.IntegerField(default=0)),
                ('sentences_correct_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
