# Generated by Django 5.2.6 on 2025-09-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='words_know_count',
            new_name='words_known_count',
        ),
    ]
